// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IInspectable.ProjectExplorer.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ProjectExplorerWindowPackageGuidString = "f2f16ece-71b7-4b31-a2f1-c91aca261509";
        public static Guid ProjectExplorerWindowPackageGuid = new Guid(ProjectExplorerWindowPackageGuidString);

        public const string ProjectExplorerWindowPackageCmdSetGuidString = "4c113c46-d7a3-45e2-926f-6504d7d796d1";
        public static Guid ProjectExplorerWindowPackageCmdSetGuid = new Guid(ProjectExplorerWindowPackageCmdSetGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectExplorerToolbar = 0x1010;
        public const int SettingsButtonContextMenu = 0x1011;
        public const int ProjectItemContextMenu = 0x1012;
        public const int ProjectExplorerCommandId = 0x0100;
        public const int ProjectExplorerSearchCommandId = 0x0101;
        public const int RefreshCommandId = 0x0102;
        public const int AddProjectCommandId = 0x0103;
        public const int RemoveProjectCommandId = 0x0104;
        public const int LoadProjectCommandId = 0x0105;
        public const int UnloadProjectCommandId = 0x0106;
        public const int SettingsCommandId = 0x0107;
        public const int OpenInFileExplorerCommandId = 0x0108;
        public const int CancelRefreshCommandId = 0x0109;
        public const int ExecuteDefaultCommandId = 0x010A;
        public const int ToolbarGroup = 0x1050;
        public const int ToolbarActionGroup = 0x1051;
        public const int ToolbarRefreshGroup = 0x1052;
        public const int SettingsButtonCtxMnuGroup = 0x1053;
        public const int ProjectItemCtxMnuDefaultGroup = 0x1054;
        public const int ProjectItemCtxMnuUnloadGroup = 0x1055;
    }
}