// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IInspectable.ProjectExplorer.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ProjectExplorerWindowPackageGuidString = "f2f16ece-71b7-4b31-a2f1-c91aca261509";
        public const string ProjectExplorerWindowPackageCmdSetGuidString = "4c113c46-d7a3-45e2-926f-6504d7d796d1";
        public static Guid ProjectExplorerWindowPackageGuid = new Guid(ProjectExplorerWindowPackageGuidString);
        public static Guid ProjectExplorerWindowPackageCmdSetGuid = new Guid(ProjectExplorerWindowPackageCmdSetGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectExplorerToolbar = 0x1010;
        public const int ProjectExplorerWindowCommandId = 0x0100;
        public const int ProjectExplorerSettingsCommandId = 0x0101;
        public const int ProjectExplorerRefreshCommandId = 0x0102;
        public const int ProjectExplorerAddProjectCommandId = 0x0103;
        public const int ProjectExplorerRemoveProjectCommandId = 0x0104;
        public const int ProjectExplorerLoadProjectCommandId = 0x0105;
        public const int ProjectExplorerUnloadProjectCommandId = 0x0106;
        public const int ProjectExplorerBuildSelectionCommandId = 0x0107;
        public const int ProjectExplorerToolbarGroup = 0x1050;
        public const int ProjectExplorerToolbarActionGroup = 0x1051;
        public const int ProjectExplorerToolbarRefreshGroup = 0x1052;
    }
}
